#page title
page_title                                : continoo                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/continoo_logo_text_small.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : continoo                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Enabling continuous Parkinson's Monitoring.                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Parkinson's disease affects 10 million people worldwide. The majority of these people are not treated at all, or if they are, they are treated in a suboptimal way due to the lack of Parkinson's experts. Medications are based on best practices and not on the individual needs of the patients as medical doctors operate on incomplete shapshot information only. 

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Henryk Borzymowski                                
your_link                                 : henryk@continoo.com                    
your_city                                 : Munich                               
email_address                             : henryk@continoo.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : conitnoo
youtube_username                          :
linkedin                                  : continoo



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Personalization
    description                           : Personalization allows targeted assessments that can vary among patients.
    fontawesome_icon_name                 : fingerprint
    
  - title                                 : Continuous
    description                           : Continuous monitoring allows trend detection and better decision making. 
    fontawesome_icon_name                 : sync

  - title                                 : Objective
    description                           : Overcome the “parking lot effect” via objective assessment of the patient’s condition.
    fontawesome_icon_name                 : bullseye

  - title                                 : Device-agnostic
    description                           : Device-agnostic software product that runs with any device (iWatch, Fitbit, …) on any OS.
    fontawesome_icon_name                 : mobile

  - title                                 : Privacy preserving
    description                           : Privacy preserving application - continoo only stores encrypted medical data.
    fontawesome_icon_name                 : shield-alt
  
  - title                                 : Telemedical approach
    description                           : Location- and time-independent assessment of the patient’s disease state.
    fontawesome_icon_name                 : user-md

  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#363b3d"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.8

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#363b3d"
app_price_color                           : "#363b3d"
app_description_color                     : "#363b3d"

feature_title_color                       : "#a194c0"
feature_text_color                        : "#7bb2c7"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
